#!/bin/bash

function display_usage {
    echo "Usage: ring-control [help|status|restart|start|stop] [daemon|load]"
    exit 1;
}

function check_service {
    case $1 in
	daemon)
	    echo -n "$1 "
	    ;;
	load)
	    echo -n "$1 "
	    ;;
	*)
	    echo "ERROR: must enter a service, 'daemon' or 'load'"
	    exit 1
	    ;;
    esac
}

########################################################################
# Main routine
########################################################################

if [ "$1" = "" ]
then
    display_usage
fi

case $1 in
    help)
	display_usage
	;;
    status)
	echo "====================================================="
	systemctl status ring-daemon
	echo "====================================================="
	systemctl status ring-load
	;;
    restart)
	check_service $2
	echo "restarting =========================================="
	systemctl restart ring-$2
	;;
    start)
	check_service $2
	echo "starting ============================================"
	systemctl start ring-$2
	;;
    stop)
	check_service $2
	echo "stopping ============================================"
	systemctl stop ring-$2
	;;
    *)
	echo "ERROR: unknown action"
	display_usage
	;;
esac
